name: magx_client
description: Dart Client for MagX multiplayer game server.
version: 3.1.0
repository: https://github.com/rIIh/magx_dart_client

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http: ^0.12.2
  freezed_annotation: ^0.12.0
  json_serializable: ^3.5.1
  rxdart: ^0.25.0
  msgpack_dart: ^0.0.7
  chopper: ^3.0.6
  match: ^0.3.1
  quiver: ^2.1.5
  meta: ^1.2.4

dev_dependencies:
  build_runner: ^1.10.11
  build_verify: ^1.1.1
  pedantic: ^1.9.2
  test: ^1.15.7
  uuid: ^2.2.2
  freezed: ^0.12.6
  chopper_generator: ^3.0.6
  mockito: ^4.1.3
