name: magx_client
description: Dart Client for MagX multiplayer game server.
version: 4.0.1
repository: https://github.com/rIIh/magx_dart_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  freezed_annotation: ^0.14.0
  json_serializable: ^5.0.2
  rxdart: ^0.27.2
  msgpack_dart: ^1.0.0
  chopper: ^4.0.1
  match: ^0.4.0
  quiver: ^3.0.1
  meta: ^1.7.0

dev_dependencies:
  analyzer: ^2.5.0
  build_runner: ^2.1.4
  build_verify: ^2.0.0
  pedantic: ^1.11.1
  test: ^1.18.2
  uuid: ^3.0.5
  freezed: ^0.14.0
  chopper_generator: ^4.0.2
  mockito: ^5.0.16
